weights: weights/yolor-d6-paper-573.pt
cfg: models/yolor-d6.yaml
data: data/coco.yaml
hyp: ./data/hyp.finetune.1280.yaml
epochs: 450
batch_size: 3
img_size:
- 1520
- 1520
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: 0,3,4,5,6
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: 4
log_imgs: 16
workers: 32
project: runs/train
name: yolor-d6-fine
exist_ok: false
total_batch_size: 15
world_size: 5
global_rank: 4
save_dir: runs/train/yolor-d6-fine
